### ISSUE TITLE
An error occurs if the "r" flag is added

### ISSUE THREAD

**Issue by sword141992** [stapelberg/rsyncprom#2]
I noticed an unpleasant feature: if you copy files recursively, you get an error:
```
2024/01/30 08:20:59 push gateway: "http://10.1.0.46:9091"
2024/01/30 08:20:59 Starting rsync ["rsync" "--stats" "--size-only"  "-rvW" "-m" "--timeout=300" "--time-limit=60" "/mnt/" "/opt/"]
2024/01/30 08:20:59 Parsing rsync output
2024/01/30 08:20:59 Pushing exit code 0
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/stapelberg/rsyncparse.Parse({0x8716a0, 0xc00028e010})
	/go/pkg/mod/github.com/stapelberg/rsyncparse@v0.0.0-20211228091344-84a4474990ee/rsyncparse.go:65 +0x42b
github.com/stapelberg/rsyncprom.Parse(...)
	/go/rsyncprom/rsyncprom.go:34
github.com/stapelberg/rsyncprom.WrapRsync({0x87a308, 0xc00011a000}, 0xc000115ef0, {0xc00012c040, 0xa, 0xa}, 0xc000135f00, 0xc000135f18)
	/go/rsyncprom/rsyncprom.go:93 +0x330
main.rsyncprommain()
	/go/rsyncprom/cmd/rsync-prom/main.go:75 +0x2cd
main.main()
	/go/rsyncprom/cmd/rsync-prom/main.go:79 +0x19
```
I ran the following command:

```./rsync-prom -prometheus_push_gateway http://10.1.0.46:9091 rsync --stats --size-only -rvW -m --timeout=300 --time-limit=60 /mnt/ /opt/```

But the rsunc command works fine

**Comment by stapelberg** [comment]
A panic in `rsyncparse.go:65` probably means that you didn’t start rsync with `LC_ALL=C.UTF-8` (as the rsyncprom docs ask you to). 

Of course it’s not great that the code panics, so I’ll change the code to produce a better error.

But most likely you need to set LC_ALL=C.UTF-8 when starting rsync(-prom)
