### ISSUE TITLE
Couldn't get the bytepersec value in pushgateway.

### ISSUE THREAD

**Issue by thava-lxcxfxr** [stapelberg/rsyncprom#4]
![image](https://github.com/stapelberg/rsyncprom/assets/66932406/7d00297a-ee44-48ae-975f-d24575438967)

**Comment by thava-lxcxfxr** [comment]
![image](https://github.com/stapelberg/rsyncprom/assets/66932406/87b32e82-9dd2-4160-aaa8-a1204438e635)

Still not getting the output sir. I have installed the latest rsync-prom@latest. Thanks

**Comment by stapelberg** [comment]
Try running your go install command with the environment variable `GOPROXY=direct`, I suspect you’re still getting an old version from the Go module proxy. 

With the latest version, the metric does show up for me:

![2024-05-19-s2d](https://github.com/stapelberg/rsyncprom/assets/55506/e1b9aad6-c9da-4414-b88a-d78a51e372ff)

**Comment by thava-lxcxfxr** [comment]
> Try running your go install command with the environment variable `GOPROXY=direct`, I suspect you’re still getting an old version from the Go module proxy.
> 
> With the latest version, the metric does show up for me:
> 
> ![2024-05-19-s2d](https://private-user-images.githubusercontent.com/55506/331857023-e1b9aad6-c9da-4414-b88a-d78a51e372ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDY2MTYsIm5iZiI6MTcxNjEwNjMxNiwicGF0aCI6Ii81NTUwNi8zMzE4NTcwMjMtZTFiOWFhZDYtYzlkYS00NDE0LWI4OGEtZDc4YTUxZTM3MmZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZGMyMGI0MjJmM2ZmNTNlOGMzNmRmN2FiZDM4ODg4ZTBiMGM2NTBiOTVjZTVjMThjZTkzNGZmZGVlMDY4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXsUvjvGz50FcfNgPZbf--GB2mfq-shWgESbc5B-snI)

Worked sir. Thanks
